dpdk: fix QA error by updating Python shebangs
Issue: LINUXEXEC-36630

Resolve package QA issues caused by Marvell CI test scripts using the
deprecated "/usr/bin/python" interpreter path. Updated shebangs to
"/usr/bin/python3" to ensure compatibility with Python3 only
environments.

ERROR: dpdk-23.11.1-r0.wr2413 do_package_qa: QA Issue:
/usr/bin/cnxk/common/scapy/sendrecv.py contained in package dpdk requires
/usr/bin/python, but no providers found in RDEPENDS:dpdk? [file-rdeps]

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>