dpdk: fix QA error by updating RDEPENDS
Issue: LINUXEXEC-36630

Added "bash" to RDEPENDS to satisfy runtime dependency checks for shell
scripts. This fix following QA Issue:

ERROR: dpdk-23.11.1-r0.wr2413 do_package_qa: QA Issue:
/usr/bin/cnxk/txrx_stats/cnxk_txrx_stats.sh contained in package dpdk
requires /bin/bash, but no providers found in RDEPENDS:dpdk? [file-rdeps]

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>